include: package:flutter_lints/flutter.yaml

linter: 
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    require_trailing_commas: true
    avoid_empty_else: true
    annotate_overrides: true
    avoid_catching_errors: true
    cancel_subscriptions: true
    empty_catches: true
    null_closures: true
    prefer_double_quotes: true
    prefer_relative_imports: true